version: '3.5'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
     - mariadb:/var/lib/mysql
    ports:
     - 3309:3306
    network_mode: bridge
  laravel-app:
    image: creativitykills/nginx-php-server
    container_name: laravel-app
    restart: always
    environment:
      LARAVEL_APP: 1
    volumes:
     - .:/var/www
    ports:
     - 81:80
    network_mode: bridge
    links:
    - mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
    - mariadb
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mariadb
     - PMA_USER=root
     - PMA_PASSWORD=root
    restart: always
    ports:
     - 8082:80
    network_mode: bridge
volumes:
  mariadb:
    name: mariadb